name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore & test backend
        run: dotnet test
        working-directory: ConsoleApp1_vdp_sheetbuilder

      - name: Verify release publish
        run: dotnet publish ConsoleApp1_vdp_sheetbuilder/ConsoleApp1_vdp_sheetbuilder.csproj -c Release
        working-directory: ConsoleApp1_vdp_sheetbuilder

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: sheetbuilder-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: sheetbuilder-frontend

      - name: Lint
        run: npm run lint
        working-directory: sheetbuilder-frontend

      - name: Run frontend tests
        run: npm run test:run
        working-directory: sheetbuilder-frontend

      - name: Build production bundle
        run: npm run build
        working-directory: sheetbuilder-frontend
